# Generated by Django 3.2.16 on 2025-02-23 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250218_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Количество должно быть не меньше 0.01.'), django.core.validators.MaxValueValidator(limit_value=9999.99, message='Количество не может превышать 9999.99.')], verbose_name='Количество'),
        ),
    ]
